In [2]:
import numpy as np

In [43]:
#Create with a range
a=np.arange(15).reshape(3,5)

In [44]:
print(a)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [18]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

2
(3, 5)
15
int64
8


In [52]:
#Array Creation
#Single dimensional array
b=np.array([1,2,3,4])
print(b,'Type is :',type(b))
print(b.dtype, 'Shape : ',b.shape, 'Number of axes : ',b.ndim)

#Multi-dimensional array
b=np.array([(1,2,3,4),(1,2,3.1,6),(2.3,4,5,7)])
print(b,'Type is :',type(b))
print(b.dtype, 'Shape : ',b.shape, 'Number of axes : ',b.ndim)

#Better to create arrays with the planned size. It can be initialised with some content in multiple ways
#Initialised with zero
a=np.zeros((1,4))
print(a)

#Initialised with 1
print(np.ones((2,3)))

#Initialised with random values
print(np.empty((4,2)))

#Create in a range
print(np.arange(1,5,0.25))

#Use linspace in case of float
print(np.linspace(0,2*np.pi,9))

[1 2 3 4] Type is : <class 'numpy.ndarray'>
int64 Shape :  (4,) Number of axes :  1
[[1.  2.  3.  4. ]
 [1.  2.  3.1 6. ]
 [2.3 4.  5.  7. ]] Type is : <class 'numpy.ndarray'>
float64 Shape :  (3, 4) Number of axes :  2
[[0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7.07106781e-01 1.00000000e+00]
 [7.07106781e-01 1.22464680e-16]
 [7.07106781e-01 1.00000000e+00]
 [7.07106781e-01 2.44929360e-16]]
[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75]
[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]


In [106]:
#Printing and representation of arrays
#1D array
print('1D Array:\n',np.arange(6))

#2D array
print('2D Array:\n',np.arange(6).reshape(2,3))

#3D array
print('3D Array:\n',np.arange(24).reshape(2,3,4))

1D Array:
 [0 1 2 3 4 5]
2D Array:
 [[0 1 2]
 [3 4 5]]
3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [66]:
#Basic Operations
a = np.arange(20,50,5)
print(a)
b = np.arange(10,40,5)
print(b)
print(a-b)
print(b**2)
print(a<35)

[20 25 30 35 40 45]
[10 15 20 25 30 35]
[10 10 10 10 10 10]
[ 100  225  400  625  900 1225]
[ True  True  True False False False]


In [70]:
#Multiplication and Matrix product
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A*B)
#Dot multiplication
print('\n',A@B)

[[2 0]
 [0 4]]

 [[5 4]
 [3 4]]


In [78]:
#Other operators
a = np.ones((2,3), dtype=int)
print(a)
b = np.random.random((2,3))
print(b)
a*=3
print(a)
b+=a
print(b)

[[1 1 1]
 [1 1 1]]
[[0.90324557 0.70215885 0.36520132]
 [0.8360282  0.94931048 0.15193015]]
[[3 3 3]
 [3 3 3]]
[[3.90324557 3.70215885 3.36520132]
 [3.8360282  3.94931048 3.15193015]]


In [83]:
b=np.array([1,2,3,4])
print(b)
print(b.sum(), b.max(), b.min())

[1 2 3 4]
10 4 1


In [129]:
#b = np.arange(24).reshape(3,4,2)
b = np.arange(8).reshape(2,2,2) #This will basically be an array of 2 holding another array of 3 holding another array of 4
print(b)
#print(b.ndim)
#print(b.sum())
#axis=0 is sum of columns across layers, axis=1 is sum of rows within a layer
print(b.sum(axis=0),'\nAxis-1\n', b.sum(axis=1), '\nAxis-2\n',b.sum(axis=1))
print('\n Tuple sum\n',b.sum(axis=(0,1)))
print('\nMean :\n',np.mean(b,axis=0))
print('\nMedian :\n',np.median(b,axis=0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[ 4  6]
 [ 8 10]] 
Axis-1
 [[ 2  4]
 [10 12]] 
Axis-2
 [[ 2  4]
 [10 12]]

 Tuple sum
 [12 16]

Mean :
 [[2. 3.]
 [4. 5.]]

Median :
 [[2. 3.]
 [4. 5.]]


In [146]:
#Indexing, Slicing and Iterating
a = np.arange(10)**3
print(a)
print(a[2])
print(a[4:7])
print(a[:6:2]) #Equivalent to a[0:6:2)] i.e. start from 0 and end by 5 and pick every second member
a[:6:2]=-1000
print(a)
print(a[::-1]) #print the 0 till the end but in reverse
for i in a:
    print(i**(1/3))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 64 125 216]
[ 0  8 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/Users/thomas/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in power
  # This is added back by InteractiveShellApp.init_path()


In [10]:
d=np.arange(20).reshape(5,4)
print(d)
print(d[3,3])
print(d[0:2,3])
print(d[:,3])
print(d[1:3,:]) #Print for rows 1 and 2 all the columns
print(d[-1]) #Here when the column is not specified,it is taken as :, i.e. all

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
15
[3 7]
[ 3  7 11 15 19]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[16 17 18 19]


In [11]:
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [17]:
print(np.ravel(d)) #Flattens the array into a single dimensional one
print(d)
print(d.shape)
print(np.transpose(d))
print(np.transpose(d).shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
(4, 5)


In [26]:
e=np.arange(12).reshape(4,3)
print(e.shape)
print(e)
e.resize(3,4)
print(e.shape)
print(e)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
#Stacking of arrays
a=np.floor(10*np.random.random((2,2,2)))
print(a)
b=np.floor(10*np.random.random((2,2,2)))
print(b)
print('\nVertical Stacking\n',np.vstack((a,b)))
print('\nHorizontal Stacking\n',np.hstack((a,b)))

[[[4. 1.]
  [5. 8.]]

 [[6. 1.]
  [4. 5.]]]
[[[6. 6.]
  [4. 5.]]

 [[4. 8.]
  [1. 3.]]]

Vertical Stacking
 [[[4. 1.]
  [5. 8.]]

 [[6. 1.]
  [4. 5.]]

 [[6. 6.]
  [4. 5.]]

 [[4. 8.]
  [1. 3.]]]

Horizontal Stacking
 [[[4. 1.]
  [5. 8.]
  [6. 6.]
  [4. 5.]]

 [[6. 1.]
  [4. 5.]
  [4. 8.]
  [1. 3.]]]


In [ ]:
#Splitting arrays
